{
  parserClass="com.github.albanseurat.lcaplugin.language.parser.LcaParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Lca"
  psiImplClassSuffix="Impl"
  psiPackage="com.github.albanseurat.lcaplugin.psi"
  psiImplPackage="com.github.albanseurat.lcaplugin.psi.impl"

  elementTypeHolderClass="com.github.albanseurat.lcaplugin.psi.LcaTypes"
  elementTypeClass="com.github.albanseurat.lcaplugin.psi.LcaElementType"
  tokenTypeClass="com.github.albanseurat.lcaplugin.psi.LcaTokenType"

  mixin("dataset_definition")="com.github.albanseurat.lcaplugin.language.psi.mixin.DatasetDefinitionMixin"
  implements("dataset_definition")="com.intellij.psi.PsiNamedElement"

  tokens=[
      DATASET_KEYWORD= 'dataset'
      INPUTS_KEYWORD = 'inputs'
      PRODUCTS_KEYWORD = 'products'
      RESOURCES_KEYWORD = 'resources'
      EMISSIONS_KEYWORD = 'emissions'
      IDENTIFIER = "regexp:\w+"
      NUMBER = "regexp:\d+"
      LBRACE = '{'
      RBRACE = '}'
      LIST_ITEM = '-'
      SPACE = "regexp:\s+"
  ]
}

lcaFile ::= dataset_definition*

dataset_definition ::= DATASET_KEYWORD IDENTIFIER LBRACE dataset_body RBRACE

dataset_body ::= products? inputs? resources? emissions?

inputs ::= INPUTS_KEYWORD LBRACE exchanges RBRACE

products ::= PRODUCTS_KEYWORD LBRACE exchanges RBRACE

resources ::= RESOURCES_KEYWORD LBRACE exchanges RBRACE

emissions ::= EMISSIONS_KEYWORD LBRACE exchanges RBRACE

exchanges ::= exchange*

exchange ::= LIST_ITEM IDENTIFIER NUMBER IDENTIFIER